version: '3.8'

services: # Solo una vez
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - "5000:5000"
    environment:
      DB_HOST: host.docker.internal
      DB_USER: ${MYSQL_USER}
      DB_PASSWORD: ${MYSQL_PASSWORD}
      DB_NAME: ${MYSQL_DATABASE}
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}
      GOOGLE_REDIRECT_URI: ${GOOGLE_REDIRECT_URI}
    volumes:
      - ./backend/uploads:/usr/src/app/uploads
    networks:
      - app-network

  frontend: # <-- Este 'frontend' debe estar al mismo nivel de indentación que 'backend'
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "80:80"
    environment:
      REACT_APP_API_URL: http://localhost:5000
      REACT_APP_GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      REACT_APP_GOOGLE_REDIRECT_URI: ${GOOGLE_REDIRECT_URI}
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge