# Usa una imagen base de Node.js
FROM node:18-alpine

# Establece el directorio de trabajo dentro del contenedor
WORKDIR /usr/src/app

# Copia los archivos package.json y package-lock.json (si existe)
COPY package*.json ./

# Instala las dependencias
RUN npm install

# Copia el resto del código de la aplicación
COPY . .

# Expone el puerto en el que tu aplicación Express escucha
EXPOSE 5000 

# Comando para iniciar la aplicación (usa el script 'start' de package.json)
CMD ["npm", "start"]